ALTER TABLE public.bonecos 
  ADD COLUMN IF NOT EXISTS full_bless boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tibia_coins integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS magic_level integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fist integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS club integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sword_skill integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS axe integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS distance integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shielding integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS premium_active boolean NOT NULL DEFAULT false;